### ISSUE TITLE
Replays not replaying correctly for doubles stock stealing.

### ISSUE THREAD

**Issue by Jinko48** [project-slippi/project-slippi#21]
It seems that doubles gameplay works for the most part in the replays, but things start getting wacky when a teammate takes a stock from their teammate who is still alive. To be more precise, after hitting start to steal a stock from a teammate, in the replay no stock is stolen and the teammate who stole the stock never respawns, which ends up causing all kinds of unpredictable replay behavior since there should be another player on screen interacting with the other players.

**Comment by JLaferri** [comment]
This bug has been fixed but the fix is not yet part of a release. Old replays where this was happening will work with this fix. Here were the ASM changes involed: https://github.com/project-slippi/slippi-ssbm-asm/compare/e830214baf1467fe0de5358b8031480b7ea10f00...master

There were also changes to Dolphin to support this new code.
